### ISSUE TITLE
Graghbasedtracking

### ISSUE THREAD

**Issue by Jarvan-hhh** [roth-hex-lab/gbot#1]
![Graghbasedtracking](https://github.com/roth-hex-lab/gbot/assets/119782232/183c12df-0207-4e25-b0a3-797fa36487b8)
I can't find the corresponding part of this framework in the code, please tell me where this part is, thank you

**Comment by lishiyu005** [comment]
Thank you for your interests. Currently we are cleaning the code. We will release the tracking part soon.

**Comment by lishiyu005** [comment]
We update the code for graph-based tracking.
