### ISSUE TITLE
Unity simulation

### ISSUE THREAD

**Issue by DavidJimenezS** [roth-hex-lab/gbot#2]
Hey guys great work. 

I was wondering how did you generate the keypoints on unity and how do you determined the visibility?

Thanks in advance for your help.

**Comment by lishiyu005** [comment]
We use python to generate key points. We don't decide visibility. We assume all points are visible.

**Comment by DavidJimenezS** [comment]
Oh ok, got many thanks for that. So, you apply FPS over the default orientation and posuition of the tool from the ply file right?

and based on that reference you apply the ransac algorithm to get the rotation from the inference?

**Comment by lishiyu005** [comment]
Yes, you get it. You can use open3d to do FPS. Then you can get 6d pose by ransac pnp.
Here is the code:
import open3d as o3d
ply_point_cloud = o3d.data.PLYPointCloud()
pcd = o3d.t.io.read_point_cloud(ply_point_cloud.path)
print("Downsample the point cloud by selecting 17 farthest points.")
downpcd_farthest = pcd.farthest_point_down_sample(17)
o3d.visualization.draw_geometries([downpcd_farthest.to_legacy()],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

**Comment by DavidJimenezS** [comment]
That's nice many thanks for your help.
